const Menu = [
    {
        id: 1,
        image: "images/buttermilk-pancakes-01.jpg",
        name: "Pan Cake",
        category: "Breakfast",
        price: 25,
        description: "A pancake is a thin, flat, circular piece of cooked batter made from milk, flour, and eggs.",
    },
    {
        id: 2,
        image: "images/daal chawal roti chawal.jpg",
        name: "Veg Thali",
        category: "Lunch",
        price: 100,
        description: "Dal Chawal is the ultimate comfort food. And maybe go-to weeknight meal for many!",
    },
    {
        id: 3,
        image: "images/aloo-samosa.jpg",
        name: "Samosa",
        category: "Snacks",
        price: 20,
        description: "A samosa is a fried or baked pastry with a savory filling, including ingredients such as spiced potatoes, onions, and peas.",
    },
    {
        id: 4,
        image: "images/Donat.jpg",
        name: "donat",
        category: "Snacks",
        price: 25,
        description: "A donut is a round, deep fried cake, usually with a hole in the center. Your favorite breakfast might be a chocolate donut and a cup of coffee.",
    },
    {
        id: 5,
        image: "images/egg burger.jpg",
        name: "Burger",
        category: "Snacks",
        price: 50,
        description: "A burger is a flat round mass of minced meat or vegetables, which is fried and often eaten in a bread roll.",
    },
    {
        id: 6,
        image: "images/godzilla milkshake.jpg",
        name: "Godzilla Milkshake",
        category: "Snacks",
        price: 60,
        description: "A milkshake is a sweet beverage made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, caramel sauce, chocolate syrup, fruit syrup, or whole fruit into a thick, sweet, cold mixture.",
    },
    {
        id: 7,
        image: "images/Idli-Dosa-Batter-4.jpg",
        name: "Idli-Dosa",
        category: "Breakfast",
        price: 25,
        description: "Idli is a savory rice cake, made by steaming a batter consisting of lentils and rice. Dosa is a crispy crepe made with the same batter of lentils and rice.",
    },
    {
        id: 8,
        image: "images/Indian Thali.jpg",
        name: "Indian Thali",
        category: "Dinner",
        price: 100,
        description: "Thali (meaning 'plate') or Bhojanam (meaning 'full meal') is a round platter used to serve food in South Asia, Southeast Asia and the Caribbean.",
    },
    {
        id: 9,
        image: "images/matar panner.jpg",
        name: "Matar Panner",
        category: "Dinner",
        price: 120,
        description: "It is a paneer (fresh cheese) and matar (peas) stew with a spicy and slightly sweet sauce accompanied by fresh cilantro.",
    },
    {
        id: 10,
        image: "images/momos.jpg",
        name: "Momos",
        category: "Snacks",
        price: 50,
        description: "Momos are bite-size dumplings made with a spoonful of stuffing wrapped in dough.",
    },
    {
        id: 11,
        image: "images/noodles.jpg",
        name: "Maggi",
        category: "Breakfast",
        price: 30,
        description: "It is a delious taste and I Love Maggi really oo yues.Lorem ipsum dolor sit amet.",
    },
    {
        id: 12,
        image: "images/pizza.jpg",
        name: "Pizza",
        category: "Snacks",
        price: 250,
        description: "Pizza ia a umami is a rich and savory flavor that your taste buds taste and recognize.",
    },
    {
        id: 13,
        image: "images/rajma chawal.jpg",
        name: "Rajma Chawal",
        category: "Lunch",
        price: 80,
        description: "Rajma chawal is a simple yet delicious meal. Rajma is rich and iron and protein when it is combined with rice it is a great source of carbohydrates.",
    },
    {
        id: 14,
        image: "images/rasgula.jpg",
        name: "Rasgulla",
        category: "Sweet",
        price: 15,
        description: "Rasgulla is a milk based popular Indian dessert orginated from Bengal yet equally loved all over India.",
    },
    {
        id: 15,
        image: "images/kalakand.jpg",
        name: "Kalakand",
        category: "Sweet",
        price: 10,
        description: "Kalakand, or qalaqand or 'kalakanu' is a popular Indian sweet made out of solidified, sweetened milk and cottage cheese.",
    },
]

export default Menu;